repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure file ends with a newline
      - id: check-yaml
        name: Validate YAML files
        files: \\.(yml|yaml)$
      - id: check-json
        name: Validate JSON files

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        name: Shell script linting with shellcheck
        files: \\.(sh|bash)$

  - repo: local
    hooks:
      - id: markdownlint
        name: Lint Markdown files
        entry: npx markdownlint-cli2 '**/*.md'
        language: system
        types: [markdown]
        pass_filenames: false

      - id: commitlint
        name: Validate commit messages against Conventional Commits
        entry: npx commitlint --edit $COMMIT_MSG
        language: system
        stages: [commit-msg]