name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for conventional commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            ci
            build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
