name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for conventional commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
          requireScope: false
          headerPattern: '^(feat|fix|docs|chore|refactor)(\\([a-z0-9\\-]+\\))?: .+'
          githubBaseUrl: https://api.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
